# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.5-jdk8
WORKDIR /Users/isabellestienen/Desktop/lecture_2/.git/DockerCompose/backend
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY cddb4.war /usr/local/tomcat/webapps/cddb.war